// Code generated by protoc-gen-ent. DO NOT EDIT.
// versions:
// - protoc-gen-ent v0.0.1
// - protoc  v3.12.4
// source: example/ent/schema/greeter.proto

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"time"
)

var _ time.Month
var _ entsql.Annotation
var _ index.Descriptor

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.Int32("age").Positive().Default(1),
		field.String("username").Unique(),
		field.String("nickname"),
	}
}

func (User) Edges() []ent.Edge {
	return nil
}

func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("username"),
		index.Fields("age", "nickname").Unique(),
	}
}

func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		TimeMixin{},
		DetailsMixin{},
	}
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "example_user"},
	}
}
